<a href="https://colab.research.google.com/github/shey2142/Pytorch-Projects/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

# arrays

In [4]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.28299329, 0.97861353, 0.07845742, 0.57641743],
       [0.22475837, 0.73274142, 0.45736513, 0.07332965],
       [0.15483281, 0.93543705, 0.05328837, 0.86418032]])

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.1003,  0.6365, -1.2998, -0.0142],
        [ 0.3094,  0.3665, -0.9200, -0.5600],
        [ 0.9139, -1.3215, -0.0935,  0.9827]])

In [15]:
tensor_3d = torch.zeros(2,3,4)
print(tensor_3d)
print()
print(tensor_3d.dtype)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

torch.float32


# turn numpy to tensor

In [12]:

tensor_coverted = torch.tensor(np1)
tensor_coverted

tensor([[0.2830, 0.9786, 0.0785, 0.5764],
        [0.2248, 0.7327, 0.4574, 0.0733],
        [0.1548, 0.9354, 0.0533, 0.8642]], dtype=torch.float64)

#Reshape tensors

In [16]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
# reshape if we don't know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
my_torch3 = torch.arange(10)
my_torch3.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])